# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_scsi"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5d007b9c-2800-4653-9969-19d3cb6f67b2";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a61665c8-c69b-44ca-8746-4e73bb86dad5"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
